language: node_js
node_js:
- '4.0'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_42ce6a917ad6_key -iv $encrypted_42ce6a917ad6_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- npm install -g hexo
before_script:
- git config --global user.name 'YOUR NAME'
- git config --global user.email 'YOUR EMAIL'
- git clone --depth=1 git@github.com:sabrinaluo/hexo-theme-replica.git themes/replica
script:
- hexo generate
after_success:
- hexo d
