language: node_js
node_js:
- '4.0'
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_42ce6a917ad6_key -iv $encrypted_42ce6a917ad6_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - .travis/ssh_config ~/.ssh/config
  - npm install -g hexo
before_script:
- git config --global user.name 'Sabrina Luo'
- git config --global user.email 'luohaojing@gmail.com'
- git clone --depth=1 git@github.com:sabrinaluo/hexo-theme-replica.git themes/replica
script:
- hexo generate
after_success:
- hexo d
